RDI-1896 Add emhttpsrc plugin
fluendo/gst.wasm pull request #26
Opened 2024-07-31 07:41 UTC by aslobodeniuk

2024-08-01 17:54 UTC, cfoch requested changes

2024-08-07 08:41 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +  emscripten_wget_data (src->uri, &download.data, &download.size,
with wget no, that is why I changed the solution to `fetch`

2024-08-07 08:43 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +  src->download_end = GST_CLOCK_TIME_IS_VALID (segment->stop) ?
invalid `segment->stop` is normal, it just means "play forward everything"

2024-08-07 13:56 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +  GST_DEBUG_OBJECT (src, "Requesting range '%s'", range_field);
what do you mean? It is used in the range request, we request a different range on each request

```c
  gchar range_field[256];
  gchar *headers[] = { "Range", range_field, NULL };
...
  attr.requestHeaders = (const char *const *) headers;
```

2024-08-07 14:14 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +        "URI already present as %s, updating to new URI %s", src->uri, uri);
actually it will have effect: the next range request will happen from the new uri. Note that `emscripten_wget_data` is not used in this plugin anymore, the download is done through Fetch API.

2024-08-08 08:52 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +        "URI already present as %s, updating to new URI %s", src->uri, uri);
Yes, I was commenting commit by commit. Ignore this comment.

2024-08-08 08:54 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +  emscripten_wget_data (src->uri, &download.data, &download.size,
I was commenting commit by commit, ignore this comment.

2024-08-08 09:24 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +        fetch = NULL;
Opportuinty to use g_clear_pointer.

2024-08-08 09:39 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc/gstemhttpsrc.c
> +  GST_DEBUG_OBJECT (src, "Requesting range '%s'", range_field);
Ah... I see. Sorry, I thought was only for printing purposes.

2024-08-08 10:28 UTC, cfoch requested changes

2024-08-08 10:28 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/samples/emhttpsrc/meson.build
> +  install: true,
Please, install samples files to: `gst.wasm/build/gst.wasm_web_wasm32/dist/web_wasm32/share/gst.wasm/gst-plugins-web/samples/`

2024-08-08 10:28 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/samples/emhttpsrc/main.c
> +/* Copyright (C) <2024> Fluendo S.A. <support@fluendo.com> */
Please, rename main.c to emhttpsrc-example.c to be consistent with other samples filenames.

2024-08-08 10:28 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/samples/emhttpsrc/main.c
> +#include <gst/gst.h>
Can you also add documentation of what your sample does in `gst-plugins-web/README.md`? Please, take as reference: `gst.wasm/gst.wasm/subprojects/samples/README.md`.

2024-08-09 08:50 UTC, cfoch requested changes
Can you try get it working with emrun instead of lite-server, and document how to run the example with emrun?

2024-08-09 09:11 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/samples/emhttpsrc/emhttpsrc-example.c
> +  context.pipe = gst_parse_launch ("emhttpsrc location=\"http://localhost:3000/hello.txt\" ! fakesink", NULL);
Can you change your example to use a fdsink or use an appsink to print output to the "textarea" of the default shell file.

2024-08-09 09:17 UTC, aslobodeniuk commented
> Can you try get it working with emrun instead of lite-server, and document how to run the example with emrun?

I'm not sure it's possible, since we need the server to share a file we could download

2024-08-09 13:05 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/samples/emhttpsrc/emhttpsrc-example.c
> +  context.pipe = gst_parse_launch ("emhttpsrc location=\"http://localhost:3000/hello.txt\" ! fakesink", NULL);
ok
![image](https://github.com/user-attachments/assets/ffdb349a-7f9a-4e00-9080-f5dab7515e76)

2024-08-09 13:09 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/samples/emhttpsrc/emhttpsrc-example.c
> +  context.pipe = gst_parse_launch ("emhttpsrc location=\"http://localhost:3000/hello.txt\" ! fakesink", NULL);
ok
![image](https://github.com/user-attachments/assets/14994895-25f5-48ad-96f4-3e3ec92bc3c5)

2024-08-10 16:04 UTC, cfoch requested changes

2024-08-10 16:04 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/README.md
> +lite-server
Sorry, but I want to insist with `emrun`, if using `http://0.0.0.0:6931/hello.txt` (url used by emrun) as location. Actually, it works for me but differently:

![Screenshot from 2024-08-10 17-57-35](https://github.com/user-attachments/assets/6260d648-4946-4053-a267-dc3d123b7166)

2024-08-12 08:23 UTC, cfoch approved these changes
Let's handle emrun issue in a new Jira bug. I approve for now.

2024-08-12 08:31 UTC, aslobodeniuk commented
> Let's handle emrun issue in a new Jira bug. I approve for now.

Jira bug:
https://fluendo.atlassian.net/browse/RDI-1936

2024-08-12 09:00 UTC, merged