RDI-1988 docs: Add coding style guidelines
fluendo/gst.wasm pull request #31
Opened 2024-09-05 10:39 UTC by cfoch

2024-09-05 13:38 UTC, turran requested changes

2024-09-05 13:38 UTC, turran commented on CODING_STYLE.md
> + 2. Functions (method) must be sorted by class hierarchy order, from child to parent method.
I would sort first by visibility:

- local (static)
- global (not API, but global among the library)
- public (API)

Then, usually on the local ones, I'll sort by hierarchy level.

2024-09-05 13:38 UTC, turran commented on CODING_STYLE.md
> +1. Use `GST_[ERROR/WARNING/...]_OBJECT` instead of `GST_[ERROR/WARNING/...]` if creating a new GstElement.
Actually `GstObject derivative` instead of GstElement

2024-09-05 13:38 UTC, turran commented on CODING_STYLE.md
> +2. If some information must be shown repeatedly (i.e. per buffer), use `GST_LOG` or `GST_LOG_OBJECT`.
I would use GST_TRACE for this

2024-09-05 13:51 UTC, cfoch commented on CODING_STYLE.md
> +2. If some information must be shown repeatedly (i.e. per buffer), use `GST_LOG` or `GST_LOG_OBJECT`.
I am just being redundant with what GStreamer documentation already states:

> | 6 | LOG     | Logs all log messages. These are messages for events that      |
|   |         | happen repeatedly during an object's lifetime; these include   |
|   |         | streaming and steady-state conditions. This is used for log    |
|   |         | messages that happen on every buffer in an element for example.|

https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c

I have no strong preference on it, though.

2024-09-05 14:48 UTC, cfoch commented on CODING_STYLE.md
> + 2. Functions (method) must be sorted by class hierarchy order, from child to parent method.
I added a second example here. I hope I am not adding more confusion. Please, have a look.

2024-09-06 10:53 UTC, turran reviewed
All good for me. Just one last thing, wouldn't it be better to call it CONTRIBUTING.md? or some other "standard" naming?

2024-09-10 09:35 UTC, cfoch commented
> All good for me. Just one last thing, wouldn't it be better to call it CONTRIBUTING.md? or some other "standard" naming?

It is okay to me. I also included the link @ylatuya mentioned: https://www.conventionalcommits.org/en/v1.0.0/ instead of the GNOME's one.

2024-09-12 10:09 UTC, cfoch commented
What's missing to approve (cc @turran )?

2024-09-12 10:15 UTC, turran commented on CODING_STYLE.md
> +2. If some information must be shown repeatedly (i.e. per buffer), use `GST_LOG` or `GST_LOG_OBJECT`.
Ok, it is fine then. No problem.

2024-09-12 10:20 UTC, turran commented on README.md
> +Refer to the [Coding Style guide ](CODING_STYLE.md)
This one should point to CONTRIBUTING.md

2024-09-12 16:44 UTC, merged