Add OpenGL example
fluendo/gst.wasm pull request #32
Opened 2024-09-06 15:52 UTC by turran

2024-09-20 10:57 UTC, cfoch requested changes

2024-09-20 10:57 UTC, cfoch commented on gst.wasm/subprojects/samples/gl/gl-example.c
> +  GST_PLUGIN_STATIC_DECLARE (videotestsrc);
not used, remove

2024-09-20 10:57 UTC, cfoch commented on gst.wasm/subprojects/samples/gl/meson.build
> +                   dependency('gstvideotestsrc'),
not used, remove

2024-09-20 11:21 UTC, rgonzalezfluendo commented
PR to review [GStreamer-OpenGL](https://github.com/fluendo/gstreamer/tree/wasm-main-gl-support)  branch is https://github.com/fluendo/gstreamer/pull/29

2024-09-23 08:27 UTC, rgonzalezfluendo commented
Conflicts in the examples list. Since it needs to be updated, can we sort alphabetically?

2024-09-23 10:55 UTC, cfoch requested changes

2024-09-23 10:55 UTC, cfoch commented on gst.wasm/subprojects/samples/gl/gl-example.c
> +#include <gst/emscripten/gstemscripten.h>
Not used.

2024-09-25 05:29 UTC, rgonzalezfluendo commented
The [PR updating GUW](https://github.com/fluendo/gstreamer/pull/25) has a conflict because sdl2 was removed.

Also, It's not enough to just resolve the conflict. The [PR must with GStremer's logic](https://github.com/fluendo/gstreamer/pull/25) also must be updated to change the feature base. Otherwise SDL2 commits will be treated by GUW as part of OpenGL.

<details>
 <summary>Git log w/o change the base</summary>

Note commit `8ce01e6261`:

```
* 6d2ae6a735 - (HEAD -> gst.wasm, wasm-main-wip) tests: Improve Emscripten support (10 seconds ago) <Jorge Zapata>
* b96ce5399c - Test gst_gsttoc.js fixed (10 seconds ago) <mcesariniflu>
* b24f29da2a - tmp: avoid crash in mem_unmap (10 seconds ago) <Alexander Slobodeniuk>
* 9bfdd7ca05 - tmp: use GCond in gstbus (10 seconds ago) <Alexander Slobodeniuk>
* d45926b336 - GstBufferPool: Moving from GstPoll to GAsyncQueue (10 seconds ago) <Maxim P. DEMENTYEV>
* f64e1aa2b8 - (origin/wasm-main-gl-support, wasm-main-gl-support) gl: Add support for Emscripten based WebGL backend (23 hours ago) <Jorge Zapata>
* 8ce01e6261 - bad: add emscripten helper and sdl2sink (3 months ago) <Alexander Slobodeniuk>
* ab4f76fd67 - (origin/wasm-main-openal, wasm-main-openal) openal: add -lopenal to the pkg-config (3 months ago) <Alexander Slobodeniuk>
* 7ffa32184b - openal: add emscripten support (3 months ago) <Alexander Slobodeniuk>
* dedf20fbd9 - base/audio: align function signatures to the expected ones (3 months ago) <Alexander Slobodeniuk>
* d45f4be2ad - (origin/wasm-main-test, wasm-main-test) Enable test for wasm (3 months ago) <Ruben Gonzalez>

```

</details>

2024-09-30 09:39 UTC, rgonzalezfluendo commented
https://github.com/fluendo/cerbero/tree/gst.wasm is sync.

Conflict in README.md must to be handled.

2024-09-30 10:41 UTC, merged

2024-09-30 10:50 UTC, rgonzalezfluendo commented
The [list of samples](https://github.com/fluendo/gst.wasm/blob/main/gst.wasm/subprojects/samples/ci/static/index.html) is hardcoded :(