RDI-1996 Introduce sdl2 plugin
fluendo/gst.wasm pull request #36
Opened 2024-09-16 08:12 UTC by aslobodeniuk

2024-09-17 10:31 UTC, cfoch requested changes

2024-09-17 10:31 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/ext/sdl2/gstsdl2elements.h
> +/*
Avoid headers if not needed or not reusable on external libraries: 

https://github.com/fluendo/gst.wasm/blob/main/CONTRIBUTING.md#header-files

See for reference:
- https://github.com/fluendo/gst.wasm/tree/main/gst.wasm/subprojects/gst-plugins-web/gst/emhttpsrc 
- https://github.com/fluendo/gst.wasm/blob/main/gst.wasm/subprojects/gst-plugins-web/gst/webcanvassrc/gstwebcanvassrc.cpp

They don't define a header file. We should be consistent.

2024-09-17 10:31 UTC, cfoch commented on build/gst.wasm.cbc
> +gst_commit = 'fluendo/RDI-1996'
:) ?

2024-09-17 10:31 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.c
> +    g_error ("Only one handler is supported currently, fix GMainContext!!");
Can you call GST_DEBUG_CATEGORY_INIT before so you use GST_ERROR here?

2024-09-17 10:31 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.c
> + * Copyright (C) <2024> Alexander Slobodeniuk <aslobodeniuk@fluendo.com>
```
 * Copyright 2024 Fluendo S.A.
 *  @author: Alexander Slobodeniuk <aslobodeniuk@fluendo.com>
 ``` 
?

2024-09-17 11:43 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.c
> +    g_error ("Only one handler is supported currently, fix GMainContext!!");
it's a different behaviour: g_error actually raises abort and it always prints to stderr, no matter if the logging is set or not

2024-09-17 11:45 UTC, aslobodeniuk commented on build/gst.wasm.cbc
> +gst_commit = 'fluendo/RDI-1996'
it's a commit for testing with the PR to gstreamer - to test with the CI. I'll remove this commit before merge.

2024-09-17 12:25 UTC, turran commented
The port of SDL2 to Emscripten which can be found at [github](https://github.com/libsdl-org/SDL/tree/231ea07617d8719679df87481ca4406b147539c1/src/video/emscripten) does all the magic to support SDL under an Emscripten environment. The idea of a port is that everything is hidden from the user, and he can just use SDL2 API directly. Looking at this element, it is still using emscripten-related calls, which shouldn't be there.

I understand that this might be an initial version, but take into account that the SDL2 port is still immature and has fixed/hardcoded things, like, for example, the support of setting a canvas ID, which is something that has been taken care of in the SDL3 version.

Also, you are adding a gst-lib for emscripten with the purpose of running a callback in the main thread. This is already handled as part of the glib's changes, where a GMainLoop can iterate safely on a thread.

2024-09-17 19:20 UTC, aslobodeniuk commented
> The port of SDL2 to Emscripten which can be found at [github](https://github.com/libsdl-org/SDL/tree/231ea07617d8719679df87481ca4406b147539c1/src/video/emscripten) does all the magic to support SDL under an Emscripten environment. The idea of a port is that everything is hidden from the user, and he can just use SDL2 API directly. Looking at this element, it is still using emscripten-related calls, which shouldn't be there.
> 
> I understand that this might be an initial version, but take into account that the SDL2 port is still immature and has fixed/hardcoded things, like, for example, the support of setting a canvas ID, which is something that has been taken care of in the SDL3 version.
> 
> Also, you are adding a gst-lib for emscripten with the purpose of running a callback in the main thread. This is already handled as part of the glib's changes, where a GMainLoop can iterate safely on a thread.

Do you want these changes to be done in this PR? Asking because the initial scope was to just move the plugin from gst-plugins-bad to gst.wasm

2024-09-17 19:28 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/ext/sdl2/gstsdl2elements.h
> +/*
fixed

2024-09-18 19:37 UTC, turran commented
> 
> Do you want these changes to be done in this PR? Asking because the initial scope was to just move the plugin from gst-plugins-bad to gst.wasm

Of course not. That's why I commented:

> I understand that this might be an initial version

But please, take my comment into account for further improve this.

2024-09-20 10:27 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.c
> +    g_error ("Only one handler is supported currently, fix GMainContext!!");
This will not abort the program unless you define G_DEBUG at compilation time, right? What about using GST_FIXME followed by `return;`?

2024-09-20 10:36 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.h
> + * Copyright (C) <2024> Alexander Slobodeniuk <aslobodeniuk@fluendo.com>
Fluendo S.A., author Alekander?

2024-09-20 11:23 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.c
> + * Copyright (C) <2024> Alexander Slobodeniuk <aslobodeniuk@fluendo.com>
fixed

2024-09-20 11:24 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/emscripten/gstemscripten.h
> + * Copyright (C) <2024> Alexander Slobodeniuk <aslobodeniuk@fluendo.com>
fixed

2024-09-23 06:02 UTC, cfoch approved these changes
Please, rebase.

2024-09-23 08:19 UTC, merged