Webcodecs
fluendo/gst.wasm pull request #37
Opened 2024-09-22 11:25 UTC by turran

2024-09-23 08:15 UTC, rgonzalezfluendo commented on DEVELOPMENT.md
> +not block the main thread, which can cause several UI responsiveness problems
```suggestion
Emscripten has support for proxying the GStreamer main thread into a Web Worker to
not block the browser main thread, which can cause several UI responsiveness problems
```

2024-10-03 12:41 UTC, cfoch reviewed
I have not reviewed code inside `#if 0`.

2024-10-03 12:41 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  self->decoder.call<void> ("decode", chunk);
Free `decode_data`.

2024-10-03 12:41 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  /* We keep self in the new thread Module */
What if there are multiple video decoders using the "self" property? All will conflict.

2024-10-03 12:42 UTC, cfoch requested changes
Forgot to request changes.

2024-10-03 14:14 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/meson.build
> +  'gstwebcanvassink.cpp',
I will work on top of this branch on https://fluendo.atlassian.net/browse/RDI-2050

2024-10-03 14:17 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.h
> +GST_ELEMENT_REGISTER_DECLARE (web_canvas_sink)
Remove .h file.

2024-10-03 14:18 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstweb.h
> +#define GST_WEB_AUTHOR "Fluendo S.A. <engineering@fluendo.com>"
Let's define it at meson level on config.h and remove this header file?

2024-10-03 14:37 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/meson.build
> +  c_args: gst_plugins_web_args + [
gst_plugins_web_args undefined

2024-10-03 17:16 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebrunner.h
> +  GstObject base;
Better GstObject to have a mutex

2024-10-03 17:17 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebcanvas.c
> +  gchar *canvases;
GstWebRunner, for elements that need to share a common thread. GstWebCanvas for elements that require an actual canvas to render. Both could be selected through the same GstContext mechanism and interchangeable.

2024-10-03 17:17 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecs.cpp
> +        supported |= conf_supported;
I need all the profiles to set properly the caps

2024-10-03 17:19 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  self->decoder.call<void> ("decode", chunk);
Already handled on line 406

2024-10-03 17:21 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  /* We keep self in the new thread Module */
I don't understand. Each decoder has its own self.

2024-10-03 17:22 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/meson.build
> +  c_args: gst_plugins_web_args + [
It's defined new

2024-10-03 17:23 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstweb.h
> +#define GST_WEB_AUTHOR "Fluendo S.A. <engineering@fluendo.com>"
I will keep it until all plugins are merged into a single one, gstweb.

2024-10-03 17:24 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebrunner.c
> +  g_cond_broadcast (&message->self->priv->sync_message_cond);
?

2024-10-03 17:25 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/meson.build
> +  '-O0'
Yes, this has to be normalized and used on every element. I would start normalizing this once all plugins are merged into one, at least the web related ones.

2024-10-03 17:25 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.h
> +/*
I don't like how GStreamer names memory/allocators/allocatorparams

2024-10-03 17:25 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  return NULL;
Yes, once we find the actual use case, we implement the function

2024-10-03 17:26 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  gst_web_runner_send_message (
It is done C alike. This can be improved later IMO

2024-10-03 17:27 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/meson.build
> +  'gstwebcanvassink.cpp',
Yes, that is the idea. Actually I'm not 100% sure to name it gst/web or ext/web

2024-10-03 17:29 UTC, turran commented on gst.wasm/subprojects/samples/template.html
> +<!doctype html>
I wasn't aware of this, how it works?

2024-10-03 17:30 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  self->val_canvas = val::module_property ("canvas");
This is a corner case I would prefer to handle in another way. Instead of impacting the implementation on every frame, do it a manner that is manageable. Is like passing a reference to a an X window and then destroying the window outside the app ... you wouldn't follow that approach but erroring the element directly.

2024-10-03 20:04 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  /* We keep self in the new thread Module */
I understand we are storing the self pointer in `Module.self`, and there is a global `Module`. What if multiple GstWebCodecsVideoDecoder objects store its own self pointer into `Module.self`.

2024-10-03 20:05 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebrunner.c
> +  g_cond_broadcast (&message->self->priv->sync_message_cond);
Sorry. Nevermind.

2024-10-03 20:10 UTC, cfoch commented on gst.wasm/subprojects/samples/template.html
> +<!doctype html>
Just compile using `--memoryprofiler` flags, then emrun will show this view. That's all I know.

2024-10-03 20:25 UTC, cfoch commented
Please, apply this diff to get rid of some warnings when compiling:

```
diff --git a/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp b/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
index 22f687a..48485e4 100644
--- a/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
+++ b/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
@@ -114,6 +114,8 @@ gst_web_video_frame_allocator_map_full (
     GstWebVideoFrame *mem, GstMapInfo *info, gsize size)
 {
   GST_ERROR ("Trying to map");
+
+  return NULL;
 }
 
 static void
@@ -148,7 +150,6 @@ static GstMemory *
 gst_web_video_frame_allocator_alloc (
     GstAllocator *allocator, gsize size, GstAllocationParams *params)
 {
-  GstWebVideoFrameAllocator *self = GST_WEB_VIDEO_FRAME_ALLOCATOR (allocator);
   GstWebVideoFrameAllocationParams *vf_params =
       reinterpret_cast<GstWebVideoFrameAllocationParams *> (params);
   GstWebVideoFrame *mem;
@@ -237,7 +238,6 @@ gst_web_video_frame_wrap (val video_frame, GstWebRunner *runner)
   GstWebVideoFrameAllocationSizeData allocation_size_data;
   GstAllocatorClass *allocator_class;
   GstMemory *mem;
-  gsize size;
 
   /* Create the AllocatorParams */
   /* TODO Create an gst_web_video_frame_allocation_parameters_init()
diff --git a/gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp b/gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
index e0ee73f..94833ec 100644
--- a/gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
+++ b/gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
@@ -53,6 +53,7 @@ typedef struct _GstWebCodecsVideoDecoderDecodeData
   GstVideoCodecFrame *frame;
 } GstWebCodecsVideoDecoderDecodeData;
 
+#if 0
 static void
 gst_web_codecs_video_decoder_video_frame_to_codec_frame (
     GstWebCodecsVideoDecoder *self, val video_frame, GstVideoCodecFrame *frame)
@@ -78,6 +79,7 @@ gst_web_codecs_video_decoder_video_frame_to_codec_frame (
   gst_buffer_unmap (frame->output_buffer, &map);
   GST_DEBUG_OBJECT (self, "Converted frame to C memory");
 }
+#endif
 
 static gboolean
 gst_web_codecs_video_decoder_get_format (
diff --git a/gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp b/gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
index f97bc49..af4dd8e 100644
--- a/gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
+++ b/gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
@@ -166,7 +166,6 @@ gst_web_canvas_sink_setup (gpointer data)
 {
   GstWebCanvasSinkSetupData *setup_data = (GstWebCanvasSinkSetupData *) data;
   GstWebCanvasSink *self = setup_data->self;
-  GstVideoSink *sink = GST_VIDEO_SINK (self);
 
   /* FIXME how to handle the case of multiple canvases? */
   self->val_canvas = val::module_property ("canvas");
```

2024-10-03 20:56 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/meson.build
> +libversion = '0'
It is as easy as removing this line.

2024-10-03 21:13 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.h
> +/*
It is more advantageous to use the GStreamer's naming, IMO. Anyway, no need to this now.

2024-10-03 21:15 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  gst_web_runner_send_message (
I agree.

2024-10-03 21:21 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/meson.build
> +  'gstwebcanvassink.cpp',
I am slightly more inclined to ext/ now.

2024-10-04 07:20 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebcanvas.c
> +/* FIXME until we have the property */
You mean document?

2024-10-04 07:25 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebcanvas.h
> +#endif
Fixed

2024-10-04 07:26 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebrunner.c
> +gst_web_runner_default_send_message (
I wouldn't care about this at this point of development

2024-10-04 07:30 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebrunner.c
> +    return g_thread_new (name, run, self);
Initially, I don't think that every web element would need a canvas-aware thread, if at the end we discover that it is the case we can change it, but for now, I think it is fine to not make this assumption. Think of HTML pages without a <canvas> element. There will be nothing to transfer and therefore will trigger an error.

2024-10-04 07:32 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  GST_ERROR ("Trying to map");
Fixed

2024-10-04 07:33 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  val foo = val::null ();
Fixed

2024-10-04 07:34 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> + * - Support SysyemMemory?
Fixed

2024-10-04 07:36 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +#define parent_class gst_web_canvas_sink_parent_class
Fixed

2024-10-04 07:36 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  if (!gst_web_utils_element_ensure_canvas (self, &self->canvas, self->id)) {
No need for this kind of check yet until there is a use case

2024-10-04 07:37 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  data.self = self;
This is for the sake of standardization in the code

2024-10-04 07:39 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +      g_param_spec_string ("id", "id", "id of canvas DOM element", "#canvas",
Fixed

2024-10-04 07:40 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/meson.build
> +libversion = '0'
Fixed

2024-10-04 07:50 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  mime_codec = gst_codec_utils_caps_get_mime_codec (state->caps);
Fixed

2024-10-04 07:59 UTC, turran commented
Regarding the warnings, I'll apply the patch. In any case I think the project _must_ have a warnings as errors cflag

2024-10-04 09:38 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebcanvas.c
> +/* FIXME until we have the property */
Yes, more precisely, to set `Returns: (transfer full):`.

Something like:
```
/**
 * gst_web_canvas_get_runner:
 * @self: The #GstWebCanvas
 *
 * Gets the underlying GstWebCanvasRunner.
 *
 * Returns: (transfer full): a reference to the underlying runner.
 */
 ```

2024-10-04 09:40 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebrunner.h
> +  GstObject base;
But the mutex is not used. Anyway, don't worry about it.

2024-10-04 10:43 UTC, turran commented
> Regarding the warnings, I'll apply the patch. In any case I think the project _must_ have a warnings as errors cflag

Patch applied

2024-10-04 10:44 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecs.cpp
> +/*
Ok

2024-10-04 10:45 UTC, rgonzalezfluendo commented
Unfortunately glib is used by cerbero through a patch. This PR is needed: https://github.com/fluendo/gst.wasm/pull/43

I am working in using the repo directly.

2024-10-04 10:50 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  GST_DEBUG_OBJECT (self, "End of finalize");
Ok

2024-10-04 10:55 UTC, turran commented
> Unfortunately glib is used by cerbero through a patch. This PR is needed: #43
> 
> I am working in using the repo directly.

I thought it was already like that. Thanks for taking care of this

2024-10-04 11:00 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebcanvas.c
> +/* FIXME until we have the property */
Ok

2024-10-04 11:08 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecs.cpp
> +/*
Done

2024-10-04 11:17 UTC, cfoch approved these changes
I approve. Please, squash your fixups and wait for green CI before merging.

We can create the following tasks for the future (cc @rgonzalezfluendo).

Tasks:
- Error GstWebVideoDecoder if canvas is removed. See https://github.com/fluendo/gst.wasm/pull/37#discussion_r1786610494
- Allow memory profiling in custom template. See https://github.com/fluendo/gst.wasm/pull/37#discussion_r1786789472
- Use configure_file defined on the root directory of the subproject. See https://github.com/fluendo/gst.wasm/pull/37#discussion_r1786599494
- Do not hardcode -g3 -O0. See https://github.com/fluendo/gst.wasm/pull/37#discussion_r1786598650
- Conflict in Module.self. See: https://github.com/fluendo/gst.wasm/pull/37#discussion_r1787315282

2024-10-04 11:18 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +    self->canvas = NULL;
We could use g_clear_pointer as convenient function. I am not strict on it.

2024-10-04 11:23 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +    self->canvas = NULL;
Yes, you are right, I'm old schoold

2024-10-04 11:47 UTC, merged