samples/codecs: make the playback smooth
fluendo/gst.wasm pull request #47
Opened 2024-10-09 00:15 UTC by aslobodeniuk

It's actually a lucky hack - to disable qos on the sink to make the playback smooth. But it's justified, since currently we do everything through the UI thread, so the last thing we also want to do through UI thread is to send QOS events upstream

Issue: RDI_2082

2024-10-09 14:48 UTC, turran requested changes

2024-10-09 14:48 UTC, turran commented on gst.wasm/subprojects/samples/codecs/codecs-example.c
> +                        "queue ! qtdemux ! webcodecsviddech264sw ! webcanvassink qos=false",
The queue doesn't have a real impact but I'll leave it as it is how it should be. Regarding `qos=false`, I won't add this. It is just hiding the real problem. Not sending QoS events just makes the `videodec` base class to push everything despite it will not be shown. In this particular case, even if QoS is false, the video frames are shown so it might be a problem on how the video decoder base class handles the QoS or how we inform the base class about the timestamp we are about to push

2024-10-09 15:26 UTC, turran commented on gst.wasm/subprojects/samples/codecs/codecs-example.c
> +                        "queue ! qtdemux ! webcodecsviddech264sw ! webcanvassink qos=false",
Setting `qos=false` on `webcodecsviddech264sw` gives exactly the same results. So something is happening in the decoder when handling this event.

2024-10-10 00:17 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/codecs/codecs-example.c
> +                        "queue ! qtdemux ! webcodecsviddech264sw ! webcanvassink qos=false",
I removed the qos=false, since you've already fixed the issue

2024-10-22 18:34 UTC, turran requested changes

2024-10-22 18:34 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  GST_DEBUG_OBJECT (self, "show frame");
Now that we are logging this, can we add the pts?

2024-10-22 18:34 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  GST_DEBUG_OBJECT (self, "show frame done");
Same here

2024-10-22 21:37 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  GST_DEBUG_OBJECT (self, "show frame done");
done

2024-10-22 21:42 UTC, turran approved these changes

2024-10-22 22:00 UTC, merged