RDI-2056
fluendo/gst.wasm pull request #52
Opened 2024-10-21 09:19 UTC by cfoch

2024-10-22 08:21 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webdownload/webdownload-example.c
> +  GST_PLUGIN_STATIC_REGISTER (opengl);
why do we need opengl plugin in this example?

2024-10-22 09:33 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +#include <emscripten/bind.h>
are you sure you need bind.h and threading.h from emscripten? I don't find of it's usage in the code

2024-10-22 09:35 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webdownload/meson.build
> +      gstweb_sdl2_dep,
why do you need this dep? It doesn't seem to be used in the example

2024-10-22 10:02 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  g_clear_pointer (&self->canvas, gst_object_unref);
wouldn't it be better to have this line in the "stop" method? When it's in "finalize", we hold a reference on the canvas even when the pipeline in the NULL state, and I forsee that depending on a usecase it could cause deadlocks.

2024-10-22 10:40 UTC, aslobodeniuk requested changes
asked few questions to confirm

2024-10-23 12:45 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  video_frame.call<val> ("copyTo", buf_data_view, options).await ();
Do you mean that I should not call `copyTo` at all?

---
These are the options AFAIK to get VideoFrame's data in system memory:
1. copyTo
2. Through an intermediate canvas, with _getImageData_ (only in srgb and display-p3").

Isn't _getImageData_ implying a copy, too?

2024-10-23 13:16 UTC, cfoch commented on gst.wasm/subprojects/samples/webdownload/webdownload-example.c
> +  GST_PLUGIN_STATIC_REGISTER (opengl);
I got the following error:
```
pthread_create: failed to transfer control of canvas "canvas" to OffscreenCanvas! Error: ReferenceError: GL is not defined
```

Just figured out that removing `-sOFFSCREENCANVAS_SUPPORT` fixes this erorr.

2024-10-23 13:18 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +#include <emscripten/bind.h>
Not needed.

2024-10-23 13:19 UTC, cfoch commented on gst.wasm/subprojects/samples/webdownload/meson.build
> +      gstweb_sdl2_dep,
Not needed.

2024-10-23 13:19 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  g_clear_pointer (&self->canvas, gst_object_unref);
I agree

2024-10-23 20:41 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webdownload/webdownload-example.c
> +  GST_PLUGIN_STATIC_REGISTER (opengl);
I assume that opengl plugin initializes OpenGL

2024-10-23 21:22 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  video_frame.call<val> ("copyTo", buf_data_view, options).await ();
Implementing [gst_web_video_frame_allocator_map_full](https://github.com/fluendo/gst.wasm/blob/main/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp#L113) is out of scope.

With gst_memory_map we can only map to the current format of the GstWebVideoFrame. We cannot map into a different format. We need to implement something like [gst_video_frame_map](https://github.com/fluendo/gst.wasm/blob/main/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp#L113): _gst_web_video_frame_map_. It receives a GstVideoInfo as argument, that is useful to map to a different format.

2024-10-23 21:59 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  video_frame.call<val> ("copyTo", buf_data_view, options).await ();
This a download element,  not a converter. Is about downloading from gpu memory to CPU. Not all future memory types will handle such a convert.

2024-10-24 11:07 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  video_frame.call<val> ("copyTo", buf_data_view, options).await ();
I don't think the `gst_video_frame_map` does any conversion. It just helps you get the system memory representation of the frame without worrying yourself of the corresponding `meta`s

2024-10-24 11:10 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.cpp
> +  if (!gst_web_utils_element_ensure_canvas (
You don't need a canvas in this element. The input `GstBuffer` which holds a `GstWebVideoFrame` memory already owns a `GstWebRunner`, that's why calling the methods directly to that API is better.

2024-10-28 22:46 UTC, turran requested changes

2024-10-28 22:46 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebutils.h
> +GstVideoFormat gst_web_utils_convert_video_frame_format (
Try to use the "namespace" of the object first after utlils, instead of the verb. For example, `gst_web_utils_video_format_from_web_format`, or `gst_web_utils_video_format_from_string`, etc.

2024-10-28 22:46 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +// #if 0
spurious comment

2024-10-28 22:46 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +    .self = self, .data = NULL, .size = size, .info = NULL, .result = FALSE
Weird indentation, I would prefer:

```c
 GstWebVideoFrameAllocatorMapCpuData data = {
    .self = self,
    .data = NULL,
    .size = size,
    .info = NULL,
    .result = FALSE
```

2024-10-28 22:46 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.c
> +gst_web_download_init (GstWebDownload *self)
This one shold be before the `class_init`

2024-10-29 09:32 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +    .self = self, .data = NULL, .size = size, .info = NULL, .result = FALSE
This is what pre-commit/clang-format enforces

2024-10-31 08:59 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +      info == NULL || (info != NULL && info->finfo != NULL), FALSE);
not a requirement, but since we always use `data`, 
```c
g_return_val_if_fail (data != NULL, FALSE);
```
would be nice IMHO

2024-10-31 09:02 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +    .self = self, .data = NULL, .size = size, .info = NULL, .result = FALSE
+1, not a requirement, but it could be
```c
 GstWebVideoFrameAllocatorMapCpuData data = {
// clang-format off
    .self = self,
    .data = NULL,
    .size = size,
    .info = NULL,
    .result = FALSE
// clang-format on
};
```

2024-10-31 09:08 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebdownload.c
> +  // TODO: Check vinfo.size coincides with GstWebVideoFrame size?
this can be easily achieved by just reordering the actions

```c
  if (!gst_buffer_map (inbuf, &in_map, GST_MAP_READ)) {
    GST_ERROR_OBJECT (self, "Failed to map inpput buffer.");
    goto unmap_outbuf;
  }

 g_warn_if_fail (self->vinfo.size == in_map.size);
*outbuf = gst_buffer_new_allocate (NULL, in_map.size, NULL);

  if (!gst_buffer_map (*outbuf, &out_map, GST_MAP_WRITE)) {
    GST_ERROR_OBJECT (self, "Failed to map output buffer.");
    g_clear_pointer (outbuf, gst_buffer_unref);
    goto beach;
  }
```

2024-10-31 09:14 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
>    GST_FIXME ("Trying to unmap");
why this log message?

2024-10-31 09:14 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
>    GST_FIXME ("Trying to unmap");
oh, it was before the PR, so it should be removed IMHO

2024-10-31 09:18 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  g_assert (data.result);
following these lines
https://github.com/fluendo/gst.wasm/pull/52/files#diff-4475ac3b8f1537763ea058b8a472431bc745aa6390ee6dc21613b677dfb027f0R140

the result can be NULL if the format is not supported. So that another code considers failure as a non-fatal case. Probably we should just return NULL instead of crashing then

2024-10-31 09:31 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebutils.c
> +      GST_ERROR ("Unsupported GstVideoFormat: %d", format);
not a requirement, but IMHO would be better
```c
    switch (format) {
    case GST_VIDEO_FORMAT_I420:
      return "I420";
    case GST_VIDEO_FORMAT_A420:
      return "I420A";
    ...
   default:
      GST_ERROR ("Unsupported GstVideoFormat: %s", gst_video_format_to_string (format));
      return NULL;
´´

2024-11-04 08:46 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  g_assert (data.result);
Does GStreamer support NULL return from a GstMemoryMapFullFunction?

2024-11-04 08:53 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  g_assert (data.result);
yes
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gstreamer/gst/gstmemory.c?ref_type=heads#L305

2024-11-04 11:28 UTC, aslobodeniuk requested changes

2024-11-04 11:28 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webdownload/webdownload-example.c
> +      gst_parse_launch ("webfetchsrc location=" DEFAULT_URL " ! "
webstreamsrc have been merged, and I would say it should be preferred to webfetchsrc, because it downloads the data in a smoother way. Without a queue in the pipeline the playback will be more smooth.

2024-11-04 17:57 UTC, aslobodeniuk approved these changes

2024-11-04 18:04 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebutils.h
> +GstVideoFormat gst_web_utils_convert_video_frame_format (
@cfoch This isnt solved yet.
CC: @aslobodeniuk

2024-11-05 11:26 UTC, aslobodeniuk approved these changes

2024-11-05 12:05 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebutils.h
> +GstVideoFormat gst_web_utils_convert_video_frame_format (
I only fixed the specific line, but now I have fixed the line below, too.

2024-11-06 08:29 UTC, turran approved these changes

2024-11-12 15:48 UTC, merged