RDI-2060 Introduce webstreamsrc element
fluendo/gst.wasm pull request #53
Opened 2024-10-21 21:18 UTC by aslobodeniuk

2024-10-23 12:00 UTC, cfoch requested changes

2024-10-23 15:48 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +}
when a structure of GObject is allocated it's already filled with zeroes. That's why technically we don't need to init the members with false , 0 or NULL.
And from POV of the coding style it's not clear to me which way is better, that's why I decided to just not add redundant lines. Feel free to request adding this initializations.

2024-10-23 20:37 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +                          const { done, value } = await reader.read();
I doubt it's possible, since [ReadableStream API](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) doesn't seem to allow to set custom buffer, as far as I could see. This means that copying is unavoidable

2024-10-23 21:37 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +      g_param_spec_string ("location", "Location", "URI of resource to read",
"location" is a consistent property name for source elements
```
$ gst-inspect-1.0 -a |& grep "   location" | grep src
filesrc:   location            : Location of the file to read
curlhttpsrc:   location            : URI of resource to read
pushfilesrc:   location            : Location of the file to read
giosrc:   location            : URI location to read from
imagesequencesrc:   location            : Pattern to create file names of input files.  File names are created by calling sprintf() with the pattern and the current index.
multifilesrc:   location            : Pattern to create file names of input files.  File names are created by calling sprintf() with the pattern and the current index.
splitfilesrc:   location            : Wildcard pattern to match file names of the input files. If the location is an absolute path or contains directory components, only the base file name part will be considered for pattern matching. The results will be sorted.
splitmuxsrc:   location            : Glob pattern for the location of the files to read
neonhttpsrc:   location            : Location to read from
openni2src:   location            : Source uri, can be a file or a device.
rtmpsrc:   location            : Location of the RTMP url to read
rtmp2src:   location            : Location of RTMP stream to access
rtspsrc:   location            : Location of the RTSP url to read
sdpsrc:   location            : URI to SDP file (sdp:///path/to/file)
souphttpsrc:   location            : Location to read from

```

2024-10-23 21:53 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +                          const { done, value } = await reader.read();
Not really. Use a https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader I wouldn't do this right now, as it is more complex but doable

2024-10-23 21:57 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +        g_thread_new (thr_name, gst_web_stream_fetch_thread, self);
There is no need to spawn a new thread and pass the data from a queue into the streaming thread. Just use the streaming thread directly. Simplifies the code and the complexity.

2024-10-23 22:51 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +                        var cont = 1;
could you please clarify? I don't understand. The cont variable changes in the loop

2024-10-23 22:56 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +        g_thread_new (thr_name, gst_web_stream_fetch_thread, self);
makes sence, but I can't imagine how to implement it: in the JS code we have a loop that reads the from a reader object, obtained from the fetch.
Do you mean that we should obtain the reader object from the fetch and somehow use it from the C code?

2024-10-28 09:23 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +        g_thread_new (thr_name, gst_web_stream_fetch_thread, self);
@turran I've been trying to implement it and reached a point where it seems to be clear it's no possible.
The thing is that we receive chunks of data in the JS thread anyway, because they are received in a promise.
Also, note that we can't just push the buffers directly from there because of how the base class is implemented - it pushes the buffers on it's own, only allowing us to allocate and fill them.
That is why passing through an internal queue is unavoidable IMHO. The only question is if we can rewrite the code to avoid creating one more thread, but that's also tricky.

To demonstrate how the threading of the JS Streams API is done: `gst_web_stream_fetch_thread` is called from a thread that starts fetching - `0x1e6330`. And `gst_web_stream_src_chunk` is a function that is called from a promise, thread `0x22a9a8`.
```
codecs-example.js:2241 0:00:00.097860000    42   0x1e6330 ERROR           webstreamsrc gstwebstreamsrc.cpp:360:gst_web_stream_fetch_thread:<webstreamsrc0> Start fetching from https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
put_char @ codecs-example.js:2241
codecs-example.js:2241 0:00:00.334790000    42   0x22a9a8 ERROR           webstreamsrc gstwebstreamsrc.cpp:151:gst_web_stream_src_chunk:<webstreamsrc0> Received chunk of size: 983040
```

What I want to say is that even if we start fetching from the streaming thread, and somehow manage the promises, we will still have an access to the data in the JS thread, from where we can't push, because of basesrc. That is why managing an internal queue is needed anyway.

Do you think it worth it to investigate how to avoid spawning a thread here? It may complify the code, expecially error handling, since currently JS handles exceptions for us.

2024-10-28 09:27 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +        g_thread_new (thr_name, gst_web_stream_fetch_thread, self);
for example, good plugin souphttpsrc spawns a thread as well without any shame
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-plugins-good/ext/soup/gstsouphttpsrc.c?ref_type=heads#L1207

2024-10-28 09:47 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +                        var cont = 1;
Sorry, `let`.

2024-10-28 10:01 UTC, cfoch approved these changes

2024-10-28 10:01 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +G_DEFINE_TYPE_WITH_CODE (GstWebStreamSrc, gst_web_stream_src,
For coding style there are 2 options here:
1. Whether we define the function gst_web_stream_src_uri_handler_init (including its body) on the top and move G_DEFINE_TYPE_WITH_CODE to the bottom
2. Or we just declare the prototype on the top and add the definition below G_DEFINE_TYPE_WITH_CODE

Any preference @turran ?

2024-10-28 12:54 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebstreamsrc.cpp
> +        g_thread_new (thr_name, gst_web_stream_fetch_thread, self);
ok, since the element is working, and the review is done and approved by @cfoch , I've created a new task:
https://fluendo.atlassian.net/browse/RDI-2125

 I find it challenging to perform, because of exceptions handling, ownership management, etc.
 So with the merged PR we will be able to prevent ourselves from regressions.

2024-10-28 13:17 UTC, merged