RDI-2061 webcanvassink: Implement navigation interface with mouse events
fluendo/gst.wasm pull request #54
Opened 2024-10-22 14:25 UTC by cfoch

Ref #RDI-2056

2024-11-04 11:20 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +      GST_WARNING_OBJECT (self, "Event %d not handled", event_type);
Not a requirement, but I wouldn't say it's a reason for warning. We don't handle [all the mouse events provided by emscripten](https://emscripten.org/docs/api_reference/html5.h.html#id4), so we know that it will be printing a lot of warnings for no reason, while the code and the input data are correct.

2024-11-04 11:24 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webdownload/webdownload-example.c
> +      gst_parse_launch ("webfetchsrc location=" DEFAULT_URL " ! "
webstreamsrc have been introduced, and I would say it should be preferred to webfetchsrc, because it downloads the data in a smoother way. Without a queue in the pipeline the playback will be more smooth.

2024-11-04 11:26 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webdownload/webdownload-example.c
> +      gst_parse_launch ("webfetchsrc location=" DEFAULT_URL " ! "
webstreamsrc have been merged, and I would say it should be preferred to webfetchsrc, because it downloads the data in a smoother way. Without a queue in the pipeline the playback will be more smooth.

2024-11-04 11:33 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  std::make_tuple (nullptr, nullptr),
do you think this line is needed? I guess
```c++
for (const auto &it : mouse_callbacks) {
...
}
```
won't go out of the array borders

2024-11-04 11:33 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +      break;
https://github.com/fluendo/gst.wasm/pull/54/files#r1827589372

2024-11-04 11:34 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +static std::tuple<GstWebUtilsMouseCb, const char *> mouse_callbacks[] = {
const would look nice here too

2024-11-04 11:37 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +  gst_web_canvas_sink_set_mouse_event_handlers (self, FALSE);
I guess it would be better to put this line into the `stop()` virtual method instead of finalize one. Since we set the callbacks on `start()`.

2024-11-04 11:40 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +GST_DEBUG_CATEGORY_STATIC (gst_web_canvas_sink_debug_category);
looks like the target branch is a bit outdated, because these lines are already in the main one
https://github.com/fluendo/gst.wasm/blob/main/gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp#L106

2024-11-05 09:10 UTC, aslobodeniuk requested changes
asked/requested few things

2024-11-05 09:18 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +      GST_WARNING_OBJECT (self, "Event %d not handled", event_type);
I will use LOG.

2024-11-05 10:59 UTC, aslobodeniuk requested changes

2024-11-05 10:59 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/gstwebcanvassink.cpp
> +}
missing `return TRUE`.

P.S. we should really add `-Wall -Werror` to common compile flags

2024-11-05 11:03 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/codecs/codecs-example.c
> +      "example:5, webcodecs*:3, videodecoder*:3,webcanvassink:6", FALSE);
that's a big amount of log.. do you think it's needed for the sample?
maybe it was just left here from the testing...

2024-11-05 11:04 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webtransportsrc/meson.build
> +      '-lhtml5'
shouldn't we create a task to finally define a proper web plugin dependency? @turran @rgonzalezfluendo

2024-11-06 10:16 UTC, aslobodeniuk approved these changes

2024-11-11 16:07 UTC, rgonzalezfluendo commented on gst.wasm/subprojects/samples/webtransportsrc/meson.build
> +      '-lhtml5'
what do you mean by "define web plugin dependency"?

2024-11-11 16:09 UTC, rgonzalezfluendo commented on gst.wasm/subprojects/samples/webtransportsrc/meson.build
> +      '-lhtml5'
I just found `gstweb_dep` is defined twice:

* https://github.com/fluendo/gst.wasm/blob/c747d2b96c72e2c139bbfe3bf10b833cd311dc54/gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/meson.build#L54
* https://github.com/fluendo/gst.wasm/blob/c747d2b96c72e2c139bbfe3bf10b833cd311dc54/gst.wasm/subprojects/gst-plugins-web/gst/web/meson.build#L16

2024-11-11 18:16 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webtransportsrc/meson.build
> +      '-lhtml5'
it is defined, but it doesn't bring it's link and compile flags. We can see in this PR that once we update the web plugin link flags we have to update all the samples afterwards, when it should be done only in the dependency.

2024-11-11 18:24 UTC, rgonzalezfluendo commented on gst.wasm/subprojects/samples/webtransportsrc/meson.build
> +      '-lhtml5'
I agree with you about the expected behavior.

Feel free to create the task to handle it.

2024-11-12 09:55 UTC, aslobodeniuk commented on gst.wasm/subprojects/samples/webtransportsrc/meson.build
> +      '-lhtml5'
task created:
https://fluendo.atlassian.net/browse/RDI-2167

2024-11-12 11:54 UTC, rgonzalezfluendo commented
This branch has conflicts that must be resolved

2024-11-13 07:47 UTC, merged

2024-11-13 08:15 UTC, rgonzalezfluendo commented
@turran  This [option](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-conversation-resolution-before-merging) can be interesting:



![image](https://github.com/user-attachments/assets/0af61407-fad5-4a05-b74e-e65bb882c5d0)

2024-11-13 08:20 UTC, turran commented
Configuration set. Thanks