Rdi 2091 Add support for WebTransport src
fluendo/gst.wasm pull request #55
Opened 2024-10-23 15:46 UTC by turran

This requires the following changes:

* [x] GLib: Fix the leak using the proper function https://github.com/fluendo/glib/pull/4
* [x] GStreamer: Fix function pointer in grammar.y https://github.com/fluendo/gstreamer/pull/34
* [x] GStreamer: Enhance the GstTask and GstPad API: https://github.com/fluendo/gstreamer/pull/35
* [x] GStreamer: Fixup the pad's task replace: https://github.com/fluendo/gstreamer/pull/38

2024-10-25 08:04 UTC, rgonzalezfluendo commented
@turran after review and [integrate with guw](https://github.com/fluendo/gstreamer/pull/34#issuecomment-2437137172) https://github.com/fluendo/gstreamer/pull/34. The [next PR](https://github.com/fluendo/gstreamer/pull/35) to GStreamer is broken. 

Can you fixed?

2024-10-25 09:03 UTC, turran commented
> @turran after review and [integrate with guw](https://github.com/fluendo/gstreamer/pull/34#issuecomment-2437137172) [fluendo/gstreamer#34](https://github.com/fluendo/gstreamer/pull/34). The [next PR](https://github.com/fluendo/gstreamer/pull/35) to GStreamer is broken.
> 
> Can you fixed?

Fixed now

2024-10-25 09:51 UTC, rgonzalezfluendo commented
@turran can you add this change in this PR?

```
diff --git a/README.md b/README.md
index 639a488..e760e96 100644
--- a/README.md
+++ b/README.md
@@ -70,6 +70,7 @@ The [current status](https://github.com/fluendo/gstreamer/compare/main...fluendo
 * ⏳ `wasm-main-openal`: Add emscripten support OpenAL to play audio [(Branch link)](https://github.com/fluendo/gstreamer/tree/wasm-main-openal)
 * ⏳ `wasm-main-gl-support`: Add emscripten OpenGL backend [(Branch link)](https://github.com/fluendo/gstreamer/tree/wasm-main-gl-support)
 * ⏳ `wasm-main-videodec` [(Branch link)](https://github.com/fluendo/gstreamer/tree/wasm-main-videodec)
+* ⏳ `wasm-main-webtransport` [(Branch link)](https://github.com/fluendo/gstreamer/tree/wasm-main-webtransport)
 * ⏳ `wasm-main-wip`: Commits in progress [(Branch link)](https://github.com/fluendo/gstreamer/tree/wasm-main-wip)
 <!-- END guw gstreamer.toml markdown -->
```

2024-10-28 09:40 UTC, cfoch requested changes

2024-10-28 09:40 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +  gst_pad_resume_task (GST_BASE_SRC_PAD (GST_BASE_SRC_CAST (self)));
Why? In what moment was the paused?

2024-10-28 10:44 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +  self->reader = object.call<val> ("getReader");
If I understand correctly, we are taking an ownership or a reference on the reader here, so on stopping the `reader` has to be released somehow. OR if we don't take no reference nor ownership, then probably we should care about not to access it when its lifetime is over. I don't see any mechanism that would do that.

2024-10-28 22:18 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtaskpool.c
> +  /* Notify the caller that the thread is ready */
Actually reviewing the code, there are several locks missing, too much C&P. I'll fix them.

2024-10-28 22:22 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +    stream = self->transport.call<val> ("createBidirectionalStream")
The user can never create a unidi_%u pad, this is a src, creating a unid_%u pad only works for sinks. You see this at the pad definition with the `GST_PAD_SOMETIMES`, `GST_PAD_REQUEST`, etc.

2024-10-28 22:25 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +  if (!registered) {
This is on purpose. At this moment, you know what thread is the streaming thread. If we call this on `basesrc->start` we are calling from the thread that triggered the `change_state` function. That is _not_ the streaming thread.

2024-10-28 22:28 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +  self->reader = object.call<val> ("getReader");
The reader should be cleaned up _on_ the streaming thread and once the streaming thread fails or is over. Not at the `basesrc->stop` (if that's what you were referring to). But yes, there is no code that is "unreffing" the val. Actually there is no code of error handling yet, that's why this is a first design.

2024-10-28 22:30 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +  gst_pad_resume_task (GST_BASE_SRC_PAD (GST_BASE_SRC_CAST (self)));
> Why?

Why resume or why pause?

> In what moment was the paused?

This was paused because the `basesrc` handling of `GstFlowReturn` pauses the task (the streaming thread) for us every time the return value is > 0 and different than `GST_FLOW_OK`. A positive return value always pauses the task.

2024-10-28 22:31 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +  gst_pad_resume_task (GST_BASE_SRC_PAD (GST_BASE_SRC_CAST (self)));
Probably this is the most important thing to understand from this code. The need to:

1. Pause the streaming thread
2. Transfer the object (messages will be handled due to the emscripten main loop process)
3. Resume the streaming thread

2024-10-28 22:34 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebutils.cpp
> +    /* In this moment, the object is transfered to the main thread
Objects are always transferred _through_ the main thread as it is the one that owns the object you want to transfer. If you want to transfer to the main thread there has to be a check I guess if the destination thread _is_ the main thread and avoid another message posting. Good catch.

2024-10-28 22:34 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +  gst_element_foreach_src_pad (src, gst_web_transport_src_stream_link, pad);
Yes, it is.

2024-10-28 22:36 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +        "rbidi_%u", GST_PAD_SRC, GST_PAD_REQUEST, GST_STATIC_CAPS_ANY);
`bidi_%u` are bidirectional streams created by the server. `rbidi_%u` are created by us.

2024-10-28 22:37 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +        console.error (e);
I don't understand where the recursiveness is. This is iterative.

2024-10-29 10:38 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebutils.cpp
> +    /* In this moment, the object is transfered to the main thread
If you don't mind i'll add this once someone is using, I can not test it with the current examples. I will just put the TODO

2024-10-30 10:00 UTC, cfoch approved these changes
I approve, but please, have my comments in consideration. Hopefully, it will make the code easier to follow with them.

2024-10-30 11:10 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +    /* FIXME how to handle the case of a stream not found */
Actually, the other way around, asking for an object that doesn't exist. I don't know how to handle that in a C++ unordered array of `val`s. What `val` would it return?

2024-10-30 11:12 UTC, turran commented
> I approve, but please, have my comments in consideration. Hopefully, it will make the code easier to follow with them.

Can you please resolve the comments that are actually fixed so I can track what is missing and also your recommendations?

2024-10-30 13:25 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +    /* FIXME how to handle the case of a stream not found */
As I said, if the object is not in the streams map, then transfer a val::undefiend() object. Then, in the callback that is called (after the object in trasnferred) you can check if the object is undefined.

2024-10-30 13:26 UTC, cfoch commented
> > I approve, but please, have my comments in consideration. Hopefully, it will make the code easier to follow with them.
> 
> Can you please resolve the comments that are actually fixed so I can track what is missing and also your recommendations?

done

2024-10-30 17:23 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +        console.error (e);
Hmm, I don't think this is actually recursive; the code adding/ending a stream is called on a `Promise.then`; therefore, it is kind of a callback of an event (on the next loop iteration), but from the PoV of the code, is on the same scope.

2024-10-30 17:26 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +const gchar *gst_web_transport_src_stream_names[] = { "unidi", "bidi",
I understand this is already resolved too.

2024-10-30 17:29 UTC, merged