RDI-2126 Fix codecs sample playback until the end
fluendo/gst.wasm pull request #57
Opened 2024-10-30 21:27 UTC by aslobodeniuk

Decoder was throwing an error after 5:30 minutes of playback because of a VideoFrame leak. Apart from this few more leaks have been fixed too.

2024-10-31 09:26 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  g_free (self->priv);
Shouldn't you `delete self->priv->video_frame` here?

2024-10-31 09:31 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  g_free (self->priv);
I don't think that will call the destructor `self->priv->video_frame`.

2024-10-31 09:49 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  g_free (self->priv);
It won't, in fact there's some mistery out there, probably because the private structure have been allocated by g_new0.
It's clear that if we assign val - it increases the reverence, and in the destructor it decreases it.

https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/val.h#L388

However calling
```c++
delete self->priv->video_frame;
```
doesn't compile, furthermore, NOT deleting nor reassigning it doesn't cause VideoFrame leak. So to make this code clear, I will just rewrite this lines to C++

2024-10-31 14:59 UTC, turran requested changes

2024-10-31 14:59 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  mem->priv =
Let's not use new/delete combo here. I know it looks like C++, but is C++ only to be able to use emsripten::val as I already commented in another review. You can wrap these calls into a `gst_web_video_frame_new()` and `gst_web_video_frame_free()`. The reason for that it _can_ be used on C code and exported in the header.

2024-10-31 14:59 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/codecs/gstwebcodecsvideodecoder.cpp
> +  const int GST_WEB_CODECS_VIDEO_DECODER_MAX_DEQUEUE = 32;
Wouldn't be better to use a define for this?

2024-10-31 16:06 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  mem->priv =
The problem is that there's some C++ specific behaviour of the `val`, defined in `val.h`. val has a constructor and a destructor. If we just allocate it as a chunk of memory filled with zeroes with g_new0 - strictly speaking it's not correct. When we don't destroy it with destructor defined for it, but just free with g_free - it also doesn't sound correct.
In my opinion, given that val has constructor and destructor - allocating it with g_new0 and freeing with g_free is an UB.

Some notes from the observations:
Following val.h - when we assign something to it, it increases the reference, and in the destructor decreases it.
When we allocate the structure with g_new0 and free it with g_free, obviously the destructor of the val is not called, so there should be a leak, but for some reason there's no leak (I assume that copy constructor doesn't work in that case either, or maybe it's just a UB).

2024-11-04 09:25 UTC, aslobodeniuk commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebvideoframe.cpp
> +  mem->priv =
>  The reason for that it can be used on C code and exported in the header.

why do you think it is a problem? We don't break the C ABI anyhow here.

2024-11-04 18:06 UTC, turran approved these changes

2024-11-05 08:51 UTC, merged