RDI-2164 Add GUW TOMLs in the gst.wasm repo and install cerbero and GUW as a python
fluendo/gst.wasm pull request #61
Opened 2024-11-08 12:17 UTC by rgonzalezfluendo

2024-11-11 16:30 UTC, turran requested changes

2024-11-11 16:30 UTC, turran commented on .github/workflows/build.yaml
> +          poetry run cerbero -c build/gst.wasm.cbc bootstrap
Thinking loud here, but instead of having this code be manually executed by the developer and automatically by the CI, would it make sense to call [poetry scripts](https://python-poetry.org/docs/pyproject/#scripts) to then do `poetry run bootstrap` for example?

2024-11-11 16:30 UTC, turran commented on .github/workflows/guw.yaml
> +          poetry run guw -l debug guw/gstreamer.gst.wasm.toml sync --local
If everything is meant to be run locally, what is the purpose of this action? To know if it fails or succeeds?

2024-11-11 16:30 UTC, turran commented on .github/workflows/guw.yaml
> +          sed -i "s#git@github.com:#https://github.com/#g" guw/gstreamer.gst.wasm.toml
I understand this is pending once the credentials are store in the projects's secret, am I right?

2024-11-11 16:32 UTC, turran commented on .github/workflows/build.yaml
> +          poetry run cerbero -c build/gst.wasm.cbc bootstrap
hmm maybe not ... this is for actual scripts to be installed along the package

2024-11-11 16:40 UTC, rgonzalezfluendo commented on .github/workflows/guw.yaml
> +          sed -i "s#git@github.com:#https://github.com/#g" guw/gstreamer.gst.wasm.toml
Right.

I am thinking the best way to store in the projects's secret in a public repo.

2024-11-11 16:48 UTC, rgonzalezfluendo commented on .github/workflows/guw.yaml
> +          poetry run guw -l debug guw/gstreamer.gst.wasm.toml sync --local
we can use GitHub Actions page to check the status of the schedule jobs.

Also I will get a GitHub notification if the job fails.

Are you thinking in other type of notification?

2024-11-12 10:05 UTC, turran commented on .github/workflows/guw.yaml
> +          poetry run guw -l debug guw/gstreamer.gst.wasm.toml sync --local
That's for the notification; we can think about that later. For now, I want to make sure the purpose you thought of this action. Is it going to test if the repos are 'syncable' only? If so, who will be doing the actual sync?

2024-11-12 11:36 UTC, rgonzalezfluendo commented on .github/workflows/guw.yaml
> +          poetry run guw -l debug guw/gstreamer.gst.wasm.toml sync --local
This is the first iteration:

* Add GUW TOMLs in the `gst.wasm` repo
* Install cerbero and GUW as a python deps
* (extra) Job to check if repos are 'syncable'

The sync will handle done in other task (after handle projects's secret)

2024-11-12 11:37 UTC, rgonzalezfluendo commented on .github/workflows/guw.yaml
> +          sed -i "s#git@github.com:#https://github.com/#g" guw/gstreamer.gst.wasm.toml
It will be handle in COM-12563

2024-11-12 14:07 UTC, turran approved these changes

2024-11-12 14:57 UTC, merged