Rdi 2212
fluendo/gst.wasm pull request #64
Opened 2024-11-28 14:23 UTC by turran

2024-12-04 17:36 UTC, cfoch requested changes

2024-12-04 17:36 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +           (GstWebTransferable *) bin, msg)))
I would add it inside the switch statement just for readability inside a `case GST_MESSAGE_ELEMENT`.

2024-12-18 09:31 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +        gst_web_transferable_request_object ((GstWebTransferable *) self,
This was on purpose. From the PoV of the element, you just call one function and that's it. This narrows down the logic an element must implement which ends to be very repetitive among elements.

From the PoV of the implementation, it is fine to do different kind of processing, similar to how GstContexts are managed. You try by sending a query/event, if it is not answered, you send a message to the bus.

2024-12-18 09:39 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtransferable.cpp
> +  if (iface->can_transfer && iface->can_transfer (self, object_name)) {
A g_return_val_if_fail would make a GLib assertion if the pre-condition is not met. Not implementing such a method is not mandatory. I wouldn't assert if it is not implemeted.

2024-12-18 09:39 UTC, turran commented on gst.wasm/subprojects/samples/template.html
> +      function onPageLoad(o) {
Ok

2024-12-18 11:17 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtransferable.cpp
> +      iface->transfer (self, object_name, msg);
Reviewing the code, yes, I wanted it to return a boolean but there is no code that can actually fail on that case, at least for now. That's why there is a `can_transfer` call before in the interface code, not the element.

2024-12-18 11:20 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +           (GstWebTransferable *) bin, msg)))
This is on purpose. Adding a switch statement on the element makes the element aware of the potential messages the interface can handle for you, which breaks the contract of having the logic split.  What if the interface handles a message that is not a `GST_MESSAGE_ELEMENT`, then you need to add another `case` which is pointless. Let the interface handle the message (of whatever kind) and check the return value, that's all.

2024-12-20 16:46 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtransferable.cpp
> +    gst_web_transferable_js_worker_transfer_object (Emval.toValue ($0),
This formatting is not too bad to turn off clang-format, IMO.

2024-12-20 17:23 UTC, cfoch approved these changes
Just requesting for the comment. But is so simple change, that I will approve in advance.

Consider the rest of comments as desires/nitpicks. Feel free to implement them or not.

2024-12-20 17:23 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtransferable.cpp
> +#define GST_WEB_TRANSFERABLE_MESSAGE_REQUEST_OBJECT_NAME                      \
Isn't this an opportunity to use a GQuark?

2024-12-20 17:23 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtransferable.cpp
> +  if (iface->can_transfer && iface->can_transfer (self, object_name)) {
Ok, I agree.

2024-12-20 17:23 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst-libs/gst/web/gstwebtransferable.cpp
> +  if (g_strcmp0 (gst_structure_get_name (s),
If we use a GQuark for GST_WEB_TRANSFERABLE_MESSAGE_REQUEST_OBJECT_NAME there is no need for using strcmp.

2024-12-20 17:23 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportsrc.cpp
> +           (GstWebTransferable *) bin, msg)))
Ok, that makes sense.

2024-12-20 17:23 UTC, cfoch commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +        gst_web_transferable_request_object ((GstWebTransferable *) self,
It is still hard to follow though. A comment on the function would be useful.

2025-01-08 11:43 UTC, turran commented on gst.wasm/subprojects/gst-plugins-web/gst/web/transport/gstwebtransportstreamsrc.cpp
> +        gst_web_transferable_request_object ((GstWebTransferable *) self,
Alright

2025-01-10 09:29 UTC, merged